version: '3'

services:
    keycloak:
        image: auth-service
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            - 8080:8080
        volumes:
            - ./data/keycloak/standalone/configuration/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
            - ./data/keycloak/themes/base/email/:/opt/jboss/keycloak/themes/base/email/
    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025

